name: Sleep for 5 minutes

on:
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  sleep:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@3dd2222992cdb2c249f43fc314e8f95b8e6f26d0 # int
      with:
        egress-policy: audit

    - name: Wait for 5 minutes
      run: sleep 300
